# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
