# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-03 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_questionanswer_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
